Automatically look up the first 10.* or 192.168.* address from the interface list
The previous solution fetched the IP address only from a predefined list of
interfaces which is a rigid solution.

Also I added shellcheck and made minor improvements on the existing scripts.

diff --git a/scripts/start-stop-status b/scripts/start-stop-status
--- a/scripts/start-stop-status
+++ b/scripts/start-stop-status
@@ -1,33 +1,35 @@
 #!/bin/sh
 
-set -euo pipefail
+set -eu
 
 AIRCONNECT_DIR="/var/packages/AirConnect/target"
 
 start_airconnect ()
 {
-    LOGFILE=/tmp/airupnp.log
-    touch ${LOGFILE}
-    chown airconnect:users ${LOGFILE}
+    logfile=/tmp/airupnp.log
+    touch "${logfile}"
+    chown airconnect:users "${logfile}"
 
-    set +e
-    IP=$(/sbin/ifconfig lbr0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
-    if [ -z "$IP" ]; then
-        IP=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
-    fi
-    if [ -z "$IP" ]; then
-        IP=$(/sbin/ifconfig bond0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
-    fi
+    ips=$(ifconfig -a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v "127.0.0.1")
 
-    if [ -z "$IP" ]; then
-        echo "Failed to get IP address from lbr0/eth0/bond0 interfaces" > ${SYNOPKG_TEMP_LOGFILE}
+    if [ -z "$ips" ]; then
+        echo "Failed to get IP addresses" > "${SYNOPKG_TEMP_LOGFILE}"
         exit 1
     fi
-    set -e
 
-    PORT=49154
+    ip=$(echo "${ips}" | grep -E "^10\\." | head -n 1)
+    if [ -z "${ip}" ]; then
+        ip=$(echo "${ips}" | grep -E "^192\\.168\\." | head -n 1)
+    fi
+    if [ -z "${ip}" ]; then
+        echo "Failed to get local IP address (10.* or 192.168.*)" > "${SYNOPKG_TEMP_LOGFILE}"
+        exit 1
+    fi
 
-    su airconnect -s /bin/sh -c "${AIRCONNECT_DIR}/airupnp -b ${IP}:${PORT} -z -l 1000:2000 -f ${LOGFILE} -d all=error" >> ${LOGFILE} 2>&1
+    port=49154
+    echo "[$(date +'%T')] Starting airupnp on ${ip}:${port}" >> ${logfile}
+
+    su airconnect -s /bin/sh -c "${AIRCONNECT_DIR}/airupnp -b ${ip}:${port} -z -l 1000:2000 -f ${logfile} -d all=error" >> ${logfile} 2>&1
 }
 
 stop_airconnect ()
@@ -37,7 +39,8 @@ stop_airconnect ()
 
 airconnect_status ()
 {
-    if [ ! ps | grep airupnp | grep -v -q grep ]
+    # shellcheck disable=SC2009
+    if ! ps | grep airupnp | grep -v -q grep
     then
         return 1
     else
