Build packages for all architectures

diff --git a/scripts/start-stop-status b/scripts/start-stop-status
--- a/scripts/start-stop-status
+++ b/scripts/start-stop-status
@@ -1,27 +1,35 @@
 #!/bin/sh
 
+set -euo pipefail
+
 AIRCONNECT_DIR="/var/packages/AirConnect/target"
 
 start_airconnect ()
 {
-    LOGFILE=/tmp/airupnp-arm.log
+    LOGFILE=/tmp/airupnp.log
     touch ${LOGFILE}
     chown airconnect:users ${LOGFILE}
 
+    set +e
     IP=$(/sbin/ifconfig lbr0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
+    if [ -z "$IP" ]; then
+        echo "Failed to get IP address from lbr0 interface" > ${SYNOPKG_TEMP_LOGFILE}
+        exit 1
+    fi
+    set -e
     PORT=49154
 
-    su airconnect -s /bin/sh -c "${AIRCONNECT_DIR}/airupnp-arm -b ${IP}:${PORT} -z -l 1000:2000 -f ${LOGFILE} -d all=error" >> ${LOGFILE} 2>&1
+    su airconnect -s /bin/sh -c "${AIRCONNECT_DIR}/airupnp -b ${IP}:${PORT} -z -l 1000:2000 -f ${LOGFILE} -d all=error" >> ${LOGFILE} 2>&1
 }
 
 stop_airconnect ()
 {
-    killall -15 airupnp-arm
+    killall -15 airupnp
 }
 
 airconnect_status ()
 {
-    if [ ! ps | grep airupnp-arm | grep -v -q grep ]
+    if [ ! ps | grep airupnp | grep -v -q grep ]
     then
         return 1
     else
@@ -51,7 +59,7 @@ case $1 in
         fi
         ;;
     log)
-        echo "/tmp/airupnp-arm.log"
+        echo "/tmp/airupnp.log"
         exit 0
         ;;
     *)
